config/routes.rb
Rails.application.routes.draw do
  resources :indices
  root to: 'indices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/index.rb
class Index < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/indices_controller.rb
class IndicesController < ApplicationController
  before_action :set_index, only: %i[ show edit update destroy ]

  # GET /indices or /indices.json
  def index
    @indices = Index.all
  end

  # GET /indices/1 or /indices/1.json
  def show
  end

  # GET /indices/new
  def new
    @index = Index.new
  end

  # GET /indices/1/edit
  def edit
  end

  # POST /indices or /indices.json
  def create
    @index = Index.new(index_params)

    respond_to do |format|
      if @index.save
        format.html { redirect_to @index, notice: "Index was successfully created." }
        format.json { render :show, status: :created, location: @index }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @index.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indices/1 or /indices/1.json
  def update
    respond_to do |format|
      if @index.update(index_params)
        format.html { redirect_to @index, notice: "Index was successfully updated." }
        format.json { render :show, status: :ok, location: @index }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @index.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indices/1 or /indices/1.json
  def destroy
    @index.destroy
    respond_to do |format|
      format.html { redirect_to indices_url, notice: "Index was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_index
      @index = Index.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def index_params
      params.fetch(:index, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/indices_helper.rb
module IndicesHelper
end

app/views/indices/_form.html.erb
<%= form_with(model: index) do |form| %>
  <% if index.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(index.errors.count, "error") %> prohibited this index from being saved:</h2>

      <ul>
        <% index.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/indices/edit.html.erb
<h1>Editing Index</h1>

<%= render 'form', index: @index %>

<%= link_to 'Show', @index %> |
<%= link_to 'Back', indices_path %>

app/views/indices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Index</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indices.each do |index| %>
      <tr>
        <td><%= link_to 'Show', index %></td>
        <td><%= link_to 'Edit', edit_index_path(index) %></td>
        <td><%= link_to 'Destroy', index, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Index', new_index_path %>

app/views/indices/new.html.erb
<h1>New Index</h1>

<%= render 'form', index: @index %>

<%= link_to 'Back', indices_path %>

app/views/indices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_index_path(@index) %> |
<%= link_to 'Back', indices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnyOldApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>